const logActions = {
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  ENROLL_STUDENT: "ENROLL_STUDENT",
  DELETE_USER: "DELETE_USER",
};

export default logActions;
